In [1]:
import numpy as np
import pandas as pd
import string
import os

input_filepath="../../data/clean/"
filename="chao_tfidf_by_lga_and_from_user_name.csv"

In [2]:
tweetdf=pd.read_csv(os.path.join(input_filepath, filename),header=0, keep_default_na=False)
tweetdf

Unnamed: 0        lga   from_user_name  Unnamed: 3                      \
0               0    Bayside          0731Sus    0.000000  0.000000  0.000000   
1               1    Bayside           11Bass    0.000000  0.000000  0.000000   
2               2    Bayside         17maez17    0.000000  0.000000  0.000000   
3               3    Bayside            1JYK1    0.000000  0.000000  0.000000   
4               4    Bayside        3DogsBums    0.000000  0.000000  0.000000   
5               5    Bayside      4fthawaiian    0.000000  0.000000  0.000000   
6               6    Bayside         545strat    0.000000  0.000000  0.000000   
7               7    Bayside       577Express    0.000000  0.000000  0.000000   
8               8    Bayside         76921890    0.000000  0.000000  0.000000   
9               9    Bayside      ACampbell47    0.000000  0.000000  0.000000   
10             10    Bayside    AJauntWithJoy    0.000000  0.000000  0.000000   
11             11    Bayside        APRILAJJJ    0.000000  0.000000  0.000000   
12             12    Bayside       ASephiroth    0.000000  0.000000  0.000000   
13             13    Bayside   AarontheBaaron    0.000000  0.000000  0.000000   
14             14    Bayside         AbdTorah    0.000000  0.000000  0.000000   
15             15    Bayside          Adam_OH    0.000000  0.000000  0.000000   
16             16    Bayside      AdrianMorte    0.000000  0.000000  0.000000   
17             17    Bayside       Aipmaulana    0.000000  0.000000  0.000000   
18             18    Bayside  AirHarajukuGirl    0.000000  0.000000  0.000000   
19             19    Bayside       AlbertJllo    0.000000  0.000000  0.000000   
20             20    Bayside       AlexCanion    0.000000  0.000000  0.000000   
21             21    Bayside      AlexaNoelli    0.000000  0.000000  0.000000   
22             22    Bayside    AliChahrour94    0.000000  0.000000  0.000000   
23             23    Bayside   Alinta_Chidzey    0.000000  0.000000  0.000000   
24             24    Bayside       Alttitude1    0.000000  0.000000  0.000000   
25             25    Bayside   Always_Blessed    0.000000  0.000000  0.000000   
26             26    Bayside      AmeliaERyan    0.000000  0.000000  0.000000   
27             27    Bayside   AndrewMDesmond    0.000000  0.000000  0.000000   
28             28    Bayside      AndyPreston    0.000000  0.000000  0.000000   
29             29    Bayside   AngkieYudistia    0.000000  0.000000  0.000000   
...           ...        ...              ...         ...       ...       ...   
14401       14401  Woollahra      syazlicious    0.000000  0.000000  0.000000   
14402       14402  Woollahra  sydguitarschool    0.000000  0.000000  0.000000   
14403       14403  Woollahra        sydneyysj    0.000000  0.000000  0.000000   
14404       14404  Woollahra          tara891    0.000000  0.000000  0.000000   
14405       14405  Woollahra   taylawatterson    0.000000  0.000000  0.000000   
14406       14406  Woollahra     thatchertime    0.000000  0.000000  0.000000   
14407       14407  Woollahra        the_pherk    0.000000  0.000000  0.000000   
14408       14408  Woollahra    therealRiveLL    0.000000  0.000000  0.000000   
14409       14409  Woollahra  thevignetteroom    0.000000  0.000000  0.000000   
14410       14410  Woollahra     tildaswagton    0.000000  0.000000  0.000000   
14411       14411  Woollahra       tjrnichols    0.000000  0.000000  0.000000   
14412       14412  Woollahra     travel_daily    0.000000  0.000000  0.000000   
14413       14413  Woollahra         traxlmaz    0.000000  0.000000  0.000000   
14414       14414  Woollahra        trudderrs    0.000000  0.000000  0.000000   
14415       14415  Woollahra        tuppaware    0.000000  0.000000  0.000000   
14416       14416  Woollahra       tzungtzuli    0.000000  0.000000  0.000000   
14417       14417  Woollahra    urbanphaedrus    0.000000  0.000000  0.000000   
14418       14418  Woollahra   valenbo

In [26]:
target_df = pd.read_csv('../../data/clean/cleaned_target.csv',header=0)
target_df = target_df.fillna(value=0.1)

In [27]:
target_df = target_df[(target_df['Type']=='Rate per 100,000 population') & (target_df['Year']==2016)][['LGA','Assault - domestic violence']]
target_df

LGA  Assault - domestic violence
1300                   Albury                     544.4263
1301        Armidale Regional                     501.4681
1302                  Ballina                     255.7125
1303                Balranald                       0.1000
1304        Bathurst Regional                     438.7931
1305                  Bayside                     315.9874
1306              Bega Valley                     312.2606
1307                Bellingen                     279.2213
1308                 Berrigan                     174.9883
1309                Blacktown                     594.3767
1310                    Bland                     348.2010
1311                  Blayney                     202.2108
1312           Blue Mountains                     317.6418
1313                    Bogan                       0.1000
1314                   Bourke                       0.1000
1315               Brewarrina                       0.1000
1316              Broken Hill                     887.5576
1317                  Burwood                     187.0373
1318                    Byron                     295.8219
1319                  Cabonne                     212.8440
1320                   Camden                     277.1012
1321             Campbelltown                     578.0347
1322               Canada Bay                     116.9059
1323     Canterbury-Bankstown                     372.2850
1324               Carrathool                       0.1000
1325            Central Coast                     524.5908
1326          Central Darling                       0.1000
1327                 Cessnock                     630.7036
1328          Clarence Valley                     432.1841
1329                    Cobar                     881.6121
...                       ...                          ...
1400               Shoalhaven                     386.1383
1401                Singleton                     356.0076
1402    Snowy Monaro Regional                     261.9198
1403            Snowy Valleys                     594.1000
1404              Strathfield                     255.1322
1405         Sutherland Shire                     215.4476
1406                   Sydney                     429.9521
1407        Tamworth Regional                     550.8377
1408                   Temora                     224.5029
1409              Tenterfield                     689.9655
1410          The Hills Shire                     127.3541
1411                    Tweed                     309.2298
1412  Unincorporated Far West                       0.1000
1413       Upper Hunter Shire                     256.7840
1414      Upper Lachlan Shire                     242.3160
1415                   Uralla                     357.2008
1416              Wagga Wagga                     622.6106
1417                   Walcha                     286.2595
1418                  Walgett                    1837.0231
1419                   Warren                       0.1000
1420       Warrumbungle Shire                     513.5730
1421                 Waverley                     235.7640
1422                   Weddin                     243.7703
1423                Wentworth                     838.1503
1424               Willoughby                      93.5694
1425            Wingecarribee                     254.7381
1426              Wollondilly                     371.9191
1427               Wollongong                     374.9982
1428                Woollahra                     152.6849
1429              Yass Valley                     204.4744

[130 rows x 2 columns]

In [29]:
tweetdf = tweetdf.merge(target_df, left_on=['lga'], right_on=['LGA'])

In [36]:
X = tweetdf.iloc[:,3:-2].as_matrix()
X

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.17155635,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [43]:
y = tweetdf.iloc[:,-1].as_matrix()
y = np.log(y)
y

array([ 5.75570234,  5.75570234,  5.75570234, ...,  5.02837632,
        5.02837632,  5.02837632])

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
import time

start = time.time()

from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(max_depth=2, random_state=0)
rfr.fit(X_train, y_train)

end = time.time()
print(end - start)

13.98357105255127


In [47]:
# Predict:
rfr.score(X_test, y_test)

0.10193683593315774

In [48]:
rfr.feature_importances_

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [60]:
cols = [(idx-3, imp) for (idx, imp) in enumerate(rfr.feature_importances_) if imp > 0]
print(cols)
colnums = [tup[0] for tup in cols]

[(754, 0.0022909763983113133), (1393, 0.23277245029349877), (2242, 0.0020612919593978453), (2540, 0.0045887495250464929), (3098, 0.31979730392114836), (4188, 0.43669337709543427), (4394, 0.0017958508071629089)]


In [62]:
# idx is the index into X, need ot subtract 3 to get index into tweetdf:
tweetdf.iloc[:,colnums][0:5]

#sydneyharbour  baulkham  feels  happy international women's  \
0             0.0       0.0    0.0                          0.0   
1             0.0       0.0    0.0                          0.0   
2             0.0       0.0    0.0                          0.0   
3             0.0       0.0    0.0                          0.0   
4             0.0       0.0    0.0                          0.0   

   manager international  swipe  treat  
0                    0.0    0.0    0.0  
1                    0.0    0.0    0.0  
2                    0.0    0.0    0.0  
3                    0.0    0.0    0.0  
4                    0.0    0.0    0.0